name: flutter_wallet
description: "Unauthority (LOS) Wallet - Secure blockchain wallet with Tor privacy"
publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.4
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  crypto: ^3.0.7
  bip39: ^1.0.6
  provider: ^6.1.5+1
  socks5_proxy: ^2.1.1
  path_provider: ^2.1.2
  path: ^1.9.0
  uuid: ^4.3.3
  ffi: ^2.1.2
  flutter_secure_storage: ^9.2.4
  pointycastle: ^3.9.1
  cryptography: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
